### PR TITLE
Decouple the Request Schema from Response Schema

### PR DESCRIPTION
**Pull request by ticosax**
This will create endpoint definition files with multiple data classes

One for the request and one for the response

such as

```python
class FooRequest(BaseModel):
  field1: str


class Foo(BaseModel):
  field1: str
  id: int


def make_request(
       self: BaseApi,
        __request__: FooRequest,
    ) -> Foo:
    ...
```

### CODE REVIEW

**Comment by asyncee** [comment]
Hello, thank you for suggesting this improvement!

Can you describe what issue does it solve?

Also, it looks like this is backwards incompatible change. Backwards compatibility is very important for currently existing projects, so there should be either feature toggle or some compatibility layer.

**Comment by ticosax** [comment]
Let's say the API we consume expose a `create` endpoint for the resource `Foo` which accept one field.

could be roughly represented like this.

```python
class FooRequest(BaseModel):
  field1: str
```

But the response, contains a different set of fields. like the id. that is known only after the resource is created.

```python
class Foo(BaseModel):
  field1: str
  id: int
```

with this changeset, we can then consume the api like intended by the server.

```python
body = FooRequest(field1='bla')
response = client.foos.foo_create(body)
assert isinstance(response, Foo)
assert response.id
assert response.field1 == 'bla'
```

It is commong pattern that some fields are computed by the server, such as metadata fields like `uuid`, `created_at`, `created_by`, ...
Those fields are part of the response but never part of the requests (`readOnly`).

I agree, this is a breaking change, like #20, in fact.With a changelog, the users should be able to update gracefully.

**Comment by asyncee** [comment]
I understand what are you talking about, but the issue you are describing sounds a little strange to me in that `swagger-codegen` generates names based on `$ref` names in schema. Maybe there are a bug in the library and you are running in name clashes somehow?

I have created a little example to demonstrate (using fastapi):

```
from typing import Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class FooRequest(BaseModel):
    field1: str


class Foo(BaseModel):
    id: int
    field1: str


@app.post("/", response_model=Foo)
def read_root(req: FooRequest) -> Foo:
    return Foo(id=1, field1=req.field1)
```

As you can see, the request model is named as `FooRequest`, and response model is `Foo`. Then following openapi schema is generated:  https://pastebin.com/raw/V7q7hpYP. The most interesting parts are `#/components/schemas/FooRequest` and `#/components/schemas/Foo`.

Using this schema, following python code is generated by `swagger-codegen`:

```
class FooRequest(BaseModel):
    field1: str


class Foo(BaseModel):
    field1: str
    id: int
```

So, as you can see, in fact, the remote server decides on naming, the library just takes names from schema and uses them. Also, adding `Request` postfix may result in such names as `FooRequestRequest`, `FooInputDTORequest` and so on, which would be strange.

**Comment by ticosax** [comment]
You are completely right. This is name collision issue.
You are suggesting that the schema generator I'm using (https://github.com/tfranzel/drf-spectacular) is creating the name collision. Which is something I didn't think about.
You are probably right. I will look at this. Thanks for the pointers.
I'll close this PR in the mean time.

**Pull request closed without merging**
