### PR TITLE
Add CI with github actions

### PR DESCRIPTION
**Pull request by ticosax**
- isort
- black
- flake8
- pytest

Not tested

### CODE REVIEW

**Comment by asyncee** [comment]
Thank you for your work and time, but I prefer CI for tests and pre-commit hooks for type checks, style checks and autoformat actions.

**Comment by ticosax** [comment]
> I prefer CI for tests
 
I'm confused, that's what this PR is all about

> pre-commit hooks for type checks, style checks and autoformat actions.

Having linters as part of the CI, doesn't prevent anyone to use pre-commit hooks, they are not exclusives.


Out of curiosity, how do you make sure Pull Requests have passing tests and don't violate linter rules?

**Comment by asyncee** [comment]
Oh, i have re-read the workflow and I totally missed that all the tools run in the check mode. At first I thought that workflow will run black for example and commit changes, if any, which is, obviously, my mistake.

I will merge and test this, thank you very much for your efforts!

**Comment by ticosax** [comment]
I will rebase it

**Comment by asyncee** [comment]
Merged, thanks!

**Comment by asyncee** [comment]
I have configured and tested it — works perfect! 👍

**Pull request merged**
