### PR TITLE
Make generated client independent from swagger_codegen

### PR DESCRIPTION
**Pull request by coderfromhere**
Hi! This change makes all generated clients independent from `swagger_codegen`, which has a bunch of dependencies related to CLI, spec parsing, and testing components that I'd like to not depend on in a prod runtime environment.

Unfortunately, the client still is quite heavy as `schemathesis` alone brings the following packages:
```
Successfully installed
attrs-19.3.0
click-7.1.2
graphql-core-3.1.2
hypothesis-5.24.0
hypothesis-graphql-0.3.1
hypothesis-jsonschema-0.17.3
iniconfig-1.0.1
jsonschema-3.2.0
junit-xml-1.9
more-itertools-8.4.0
packaging-20.4
pluggy-0.13.1
py-1.9.0
pyparsing-2.4.7
pyrsistent-0.16.0
pytest-6.0.1
pytest-subtests-0.3.2
pyyaml-5.3.1
schemathesis-2.3.3
six-1.15.0
sortedcontainers-2.2.2
starlette-0.13.7
toml-0.10.1
werkzeug-1.0.1
```

I wonder if it can be removed too, as the types definitions seems to be relatively easy to replicate, and I think there's no need for `pytest`, `graphql`, and the entire `starlette` and `werkzeug ` frameworks.

### CODE REVIEW

**Comment by asyncee** [comment]
Hello and thank you for such an interesting idea!

This issue bothers me from the beginning of the project. First of all, i think we need to get rid of `schemathesis` dependency because it is too large. I just had no time to get my hands on it.

I like the idea of bundling swagger-codegen runtime into generated client.

**Comment by coderfromhere** [comment]
no worries! I've just pushed the rebased version, the default renderer should be b/w compatible

**Comment by asyncee** [comment]
I'll review and merge this in a few days

**Comment by asyncee** [comment]
Looks good, thank you!

**Comment by coderfromhere** [comment]
cool, thanks!

**Comment by asyncee** [comment]
Version 0.1.19 is released.

**Pull request merged**
